### PR TITLE
support for readTimeout and connectTimeout params

### PR DESCRIPTION
**Pull request by wyvern8**
This is to assist when working with nonchunked requests via squid proxy where the hardcoded 10sec readTimeout is exceeded for large file uploads.  Also an error handling fix for date mismatches in future.

### CODE REVIEW

**Comment by wyvern8** [comment]
@colinbendell thoughts on this PR?  we are using it locally with an increased readTimeout via squid and it has fixed our issue with large file uploads.

**Comment by wyvern8** [comment]
@colinbendell we are seeing good results with this.  Ideally do not want to maintain a fork - happy to look at updates to this PR as required for merge.

**Comment by wyvern8** [comment]
Bump @colinbendell

**Comment by wyvern8** [comment]
@colinbendell the team has forked this to our internal github.  Please let me know if you want to merge so that we revert to your repo as master and avoid an extra build etc.

**Comment by wyvern8** [comment]
@dshafik any chance you can assist with getting this PR merged?

**Comment by Sheikh-Aman** [comment]
Hi @wyvern8 ,

Other recent PR mergers have introduced some errors, when I try to merge this PR.
Can you please see if you can resolve them and ping us again?

You'd want to look into `com.akamai.netstorage.NetStorage.java`

Also, you might want to look into how Events are now being recorded through the `EventBuilder` class

**Comment by Sheikh-Aman** [comment]
Hi @wyvern8 ,

Can you please have a look at this?

**Pull request merged**
